version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-reservations-app
    restart: unless-stopped
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
